name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: windows-latest  # Вказуємо, що робоче середовище Windows

    steps:
      # 1. Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # 2. Завантаження артефакту на GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Завантажує всі файли з кореневої папки, якщо ваші файли знаходяться в корені репозиторію

      # 3. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
